### ISSUE TITLE
add support for dpad controllers

### ISSUE THREAD

**Issue by autonome** [donmccurdy/aframe-gamepad-controls#2]
Eg: http://smile.amazon.com/Retro-Nintendo-Controller-Not-Machine-Specific/dp/B0034ZOAO0/ref=sr_1_9

**Comment by donmccurdy** [comment]
Getting a controller to test this and it's still on the way (amazon prime isn't _that_ fast) but I think this should be fixed. Let me know if not, I haven't found much documentation on button mappings.

It's also possible to check the gamepad state programmatically (`gamepadControls.getDpad()`, `gamepadControls.getButton(0...N)`), or by listening for `gamepadbuttondown` events on the element. That's what you'd need to customize what different buttons do.

**Comment by autonome** [comment]
Thanks Don. Is the demo page updated? Can I test there?

**Comment by autonome** [comment]
YAY, works on desktop Firefox nightly. Still crashing Android Firefox nightly.

**Comment by autonome** [comment]
Crash bug, for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1238541
